# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy all files
COPY . .

# Install dependencies
RUN pnpm install

# Build the server
WORKDIR /app/server
RUN npm run build

# Set working directory back to /app so that relative paths work if necessary
WORKDIR /app

# Expose any required port if needed (optional)

# Run the MCP server
CMD ["node", "server/dist/cli.js"]
